import re
a="this is a string."
match=re.search(".$",a)
print(match)
match=re.findall(".",a)
print(match)
match=re.search("^th",a)
print(match)
match=re.findall("[a-z]",a)
print(match)
match=re.search("s|a",a)
print(match)
match=re.findall("[abc]",a)
print(match)
match=re.search("is?i",a)
print(match)
match=re.search("is",a)
print(match)
match=re.findall("\.",a)
print(match)
match=re.findall("a*",a)
print(match)
match =re.findall("a+",a)
print(match)
match=re.search("a{2,3}",a)
print(match)
c="acd"
match=re.search("(a|b)cd",c)
print(match)
